Susikumar first day task for understanding
visualbis/fssa-js-basics pull request #7
Opened 2023-12-12 09:19 UTC by Susikumar-Pitchaimuthu

This is the commitment to help you understand my JavaScript standards.

2023-12-14 06:48 UTC, praveenn77 requested changes

2023-12-14 06:48 UTC, praveenn77 commented on Day02/salesManager.mjs
> +  categorizeGroup(columnName, poor, neutral) {
change the argument like this
```
[{
  group: "Poor",
   from:0,
  to: 100
}, 
.....
]
```

2023-12-14 06:48 UTC, praveenn77 commented on Day01/objectCheck.mjs
> +  }
Finish this ...

2023-12-14 09:17 UTC, Susikumar-Pitchaimuthu commented
Hello sir,
I have implemented your code suggestion into my implementation. Thank you
for your input.

On Thu, Dec 14, 2023 at 12:18 PM Praveen N ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In Day02/salesManager.mjs
> <https://github.com/visualbis/fssa-js-basics/pull/7#discussion_r1426241478>
> :
>
> > @@ -0,0 +1,97 @@
> +class salesManger {
> +  values = [];
> +  header = [];
> +  constructor(data) {
> +    this.header = data[0];
> +    this.values = data.slice(1);
> +  }
> +
> +  // Add Group for the products
> +  categorizeGroup(columnName, poor, neutral) {
>
> change the argument like this
>
> [{
>   group: "Poor",
>    from:0,
>   to: 100
> },
> .....
> ]
>
> ------------------------------
>
> In Day01/objectCheck.mjs
> <https://github.com/visualbis/fssa-js-basics/pull/7#discussion_r1426242352>
> :
>
> > +  filterTheMiultipleColumnValues(columnData) {
> +    columnData.forEach((items) => {
> +
> +    })
> +  }
>
> Finish this ...
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/visualbis/fssa-js-basics/pull/7#pullrequestreview-1781050219>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4HQTXKZIRHIOH3ZLHWA65LYJKOMTAVCNFSM6AAAAABARD2THSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOOBRGA2TAMRRHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-12-15 06:27 UTC, praveenn77 requested changes

2023-12-15 06:27 UTC, praveenn77 commented on Day02/salesManager.mjs
> +    let uniqueMonths = [...new Set(this.values.map((row) => row[1]))];
```suggestion

    let uniqueProducts = new Set();
    this.values.forEach((row) => uniqueProducts.add(row[0]));
```

2023-12-15 08:51 UTC, Susikumar-Pitchaimuthu commented on Day02/salesManager.mjs
> +    let uniqueMonths = [...new Set(this.values.map((row) => row[1]))];
Hello sir, 
The code correction has been implemented

2025-01-13 22:13 UTC, closed without merging